version: '3'

services:
  wordpress:
    image: saravana227/custom-wordpress
    ports:
      - "80:80"
    volumes:
      - ./wp-config.php:/var/www/html/wp-config.php
      - ./html:/var/www/html  # Assuming your WordPress files are in the 'html' directory
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wordpress_network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wordpress_network

networks:
  wordpress_network:
    driver: bridge
