version: '3.8'

services:
  wordpress:
    build:
      context: .  # Use the current directory to build the Dockerfile
    image: custom-wordpress:latest  # Name for the custom WordPress image
    container_name: wordpress
    ports:
      - "8080:80"  # Map port 8080 on the host to port 80 in the container
    environment:
      WORDPRESS_DB_HOST: your-database-host:3306  # Replace with your actual DB host
      WORDPRESS_DB_NAME: your-database-name  # Replace with your actual DB name
      WORDPRESS_DB_USER: your-database-username  # Replace with your actual DB username
      WORDPRESS_DB_PASSWORD: your-database-password  # Replace with your actual DB password
    volumes:
      - wordpress_data:/var/www/html  # Persist WordPress data
    networks:
      - wordpress-network

volumes:
  wordpress_data:  # Named volume for WordPress data

networks:
  wordpress-network:
    driver: bridge
