version: '3.8'

services:
  wordpress:
    build:
      context: .  # Builds the WordPress image from the Dockerfile in the current directory
    image: custom-wordpress:latest  # Custom WordPress image
    container_name: wordpress
    ports:
      - "8080:80"  # Maps port 8080 on the host to port 80 in the container
    environment:
      WORDPRESS_DB_HOST: db:3306  # Connect to MySQL container on port 3306
      WORDPRESS_DB_NAME: wordpress  # Database name
      WORDPRESS_DB_USER: wordpress  # Database user
      WORDPRESS_DB_PASSWORD: wordpress  # Database user password
    volumes:
      - wordpress_data:/var/www/html  # Persist WordPress files
    depends_on:
      - db  # Ensure MySQL starts before WordPress

  db:
    image: mysql:5.7  # Official MySQL 5.7 image
    container_name: wordpress_db
    restart: always  # Restart policy for the database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Root password for MySQL
      MYSQL_DATABASE: wordpress  # Create a database named 'wordpress'
      MYSQL_USER: wordpress  # WordPress database user
      MYSQL_PASSWORD: wordpress  # Password for WordPress database user
    volumes:
      - db_data:/var/lib/mysql  # Persist MySQL data

volumes:
  wordpress_data:  # Named volume for WordPress files
  db_data:  # Named volume for MySQL data
